// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aldous_broder
arma::mat aldous_broder(const arma::mat& W, int start);
RcppExport SEXP _TreeSampleR_aldous_broder(SEXP WSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(aldous_broder(W, start));
    return rcpp_result_gen;
END_RCPP
}
// fast_cover
arma::mat fast_cover(const arma::mat& W, int start, int threshold);
RcppExport SEXP _TreeSampleR_fast_cover(SEXP WSEXP, SEXP startSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_cover(W, start, threshold));
    return rcpp_result_gen;
END_RCPP
}
// wilson
arma::mat wilson(const arma::mat& W, int start);
RcppExport SEXP _TreeSampleR_wilson(SEXP WSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(wilson(W, start));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TreeSampleR_aldous_broder", (DL_FUNC) &_TreeSampleR_aldous_broder, 2},
    {"_TreeSampleR_fast_cover", (DL_FUNC) &_TreeSampleR_fast_cover, 3},
    {"_TreeSampleR_wilson", (DL_FUNC) &_TreeSampleR_wilson, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_TreeSampleR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
