# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name aldous_broder
NULL

aldous_broder <- function(W, start) {
    .Call(`_TreeSampleR_aldous_broder`, W, start)
}

fast_cover <- function(W, start, threshold) {
    .Call(`_TreeSampleR_fast_cover`, W, start, threshold)
}

wilson <- function(W, start) {
    .Call(`_TreeSampleR_wilson`, W, start)
}

